[window]
opacity = 0.8
decorations = "None"

[font]
#normal.family = 'Courier Prime Code'
normal.family = 'HackNerdFont'
size = 18.0


# [terminal.shell]
# program = "/usr/bin/tmux"
# args = ["new-session", "-A", "-s", "default"]

